/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApplicationsIndexRouteImport } from './routes/applications/index'
import { Route as ApplicationsNewRouteImport } from './routes/applications/new'
import { Route as ApplicationsIdRouteImport } from './routes/applications/$id'
import { Route as ApplicationsIdEditRouteImport } from './routes/applications/$id/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsIndexRoute = ApplicationsIndexRouteImport.update({
  id: '/applications/',
  path: '/applications/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsNewRoute = ApplicationsNewRouteImport.update({
  id: '/applications/new',
  path: '/applications/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsIdRoute = ApplicationsIdRouteImport.update({
  id: '/applications/$id',
  path: '/applications/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsIdEditRoute = ApplicationsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ApplicationsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/applications/$id': typeof ApplicationsIdRouteWithChildren
  '/applications/new': typeof ApplicationsNewRoute
  '/applications/': typeof ApplicationsIndexRoute
  '/applications/$id/edit': typeof ApplicationsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/applications/$id': typeof ApplicationsIdRouteWithChildren
  '/applications/new': typeof ApplicationsNewRoute
  '/applications': typeof ApplicationsIndexRoute
  '/applications/$id/edit': typeof ApplicationsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/applications/$id': typeof ApplicationsIdRouteWithChildren
  '/applications/new': typeof ApplicationsNewRoute
  '/applications/': typeof ApplicationsIndexRoute
  '/applications/$id/edit': typeof ApplicationsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applications/$id'
    | '/applications/new'
    | '/applications/'
    | '/applications/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/applications/$id'
    | '/applications/new'
    | '/applications'
    | '/applications/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/applications/$id'
    | '/applications/new'
    | '/applications/'
    | '/applications/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplicationsIdRoute: typeof ApplicationsIdRouteWithChildren
  ApplicationsNewRoute: typeof ApplicationsNewRoute
  ApplicationsIndexRoute: typeof ApplicationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/': {
      id: '/applications/'
      path: '/applications'
      fullPath: '/applications/'
      preLoaderRoute: typeof ApplicationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/new': {
      id: '/applications/new'
      path: '/applications/new'
      fullPath: '/applications/new'
      preLoaderRoute: typeof ApplicationsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/$id': {
      id: '/applications/$id'
      path: '/applications/$id'
      fullPath: '/applications/$id'
      preLoaderRoute: typeof ApplicationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/$id/edit': {
      id: '/applications/$id/edit'
      path: '/edit'
      fullPath: '/applications/$id/edit'
      preLoaderRoute: typeof ApplicationsIdEditRouteImport
      parentRoute: typeof ApplicationsIdRoute
    }
  }
}

interface ApplicationsIdRouteChildren {
  ApplicationsIdEditRoute: typeof ApplicationsIdEditRoute
}

const ApplicationsIdRouteChildren: ApplicationsIdRouteChildren = {
  ApplicationsIdEditRoute: ApplicationsIdEditRoute,
}

const ApplicationsIdRouteWithChildren = ApplicationsIdRoute._addFileChildren(
  ApplicationsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplicationsIdRoute: ApplicationsIdRouteWithChildren,
  ApplicationsNewRoute: ApplicationsNewRoute,
  ApplicationsIndexRoute: ApplicationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
