/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QaIndexRouteImport } from './routes/qa/index'
import { Route as CvIndexRouteImport } from './routes/cv/index'
import { Route as ApplicationsIndexRouteImport } from './routes/applications/index'
import { Route as QaNewRouteImport } from './routes/qa/new'
import { Route as QaIdRouteImport } from './routes/qa/$id'
import { Route as CvUploadRouteImport } from './routes/cv/upload'
import { Route as ApplicationsNewRouteImport } from './routes/applications/new'
import { Route as ApplicationsIdRouteImport } from './routes/applications/$id'
import { Route as QaIdIndexRouteImport } from './routes/qa/$id/index'
import { Route as CvTailorIndexRouteImport } from './routes/cv/tailor/index'
import { Route as CvIdIndexRouteImport } from './routes/cv/$id/index'
import { Route as ApplicationsIdIndexRouteImport } from './routes/applications/$id/index'
import { Route as QaIdEditRouteImport } from './routes/qa/$id/edit'
import { Route as CvTailorHistoryRouteImport } from './routes/cv/tailor/history'
import { Route as ApplicationsIdEditRouteImport } from './routes/applications/$id/edit'
import { Route as ApiAiStreamRouteImport } from './routes/api/ai/stream'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QaIndexRoute = QaIndexRouteImport.update({
  id: '/qa/',
  path: '/qa/',
  getParentRoute: () => rootRouteImport,
} as any)
const CvIndexRoute = CvIndexRouteImport.update({
  id: '/cv/',
  path: '/cv/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsIndexRoute = ApplicationsIndexRouteImport.update({
  id: '/applications/',
  path: '/applications/',
  getParentRoute: () => rootRouteImport,
} as any)
const QaNewRoute = QaNewRouteImport.update({
  id: '/qa/new',
  path: '/qa/new',
  getParentRoute: () => rootRouteImport,
} as any)
const QaIdRoute = QaIdRouteImport.update({
  id: '/qa/$id',
  path: '/qa/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CvUploadRoute = CvUploadRouteImport.update({
  id: '/cv/upload',
  path: '/cv/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsNewRoute = ApplicationsNewRouteImport.update({
  id: '/applications/new',
  path: '/applications/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsIdRoute = ApplicationsIdRouteImport.update({
  id: '/applications/$id',
  path: '/applications/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const QaIdIndexRoute = QaIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => QaIdRoute,
} as any)
const CvTailorIndexRoute = CvTailorIndexRouteImport.update({
  id: '/cv/tailor/',
  path: '/cv/tailor/',
  getParentRoute: () => rootRouteImport,
} as any)
const CvIdIndexRoute = CvIdIndexRouteImport.update({
  id: '/cv/$id/',
  path: '/cv/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsIdIndexRoute = ApplicationsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ApplicationsIdRoute,
} as any)
const QaIdEditRoute = QaIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => QaIdRoute,
} as any)
const CvTailorHistoryRoute = CvTailorHistoryRouteImport.update({
  id: '/cv/tailor/history',
  path: '/cv/tailor/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsIdEditRoute = ApplicationsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ApplicationsIdRoute,
} as any)
const ApiAiStreamRoute = ApiAiStreamRouteImport.update({
  id: '/api/ai/stream',
  path: '/api/ai/stream',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/applications/$id': typeof ApplicationsIdRouteWithChildren
  '/applications/new': typeof ApplicationsNewRoute
  '/cv/upload': typeof CvUploadRoute
  '/qa/$id': typeof QaIdRouteWithChildren
  '/qa/new': typeof QaNewRoute
  '/applications/': typeof ApplicationsIndexRoute
  '/cv/': typeof CvIndexRoute
  '/qa/': typeof QaIndexRoute
  '/api/ai/stream': typeof ApiAiStreamRoute
  '/applications/$id/edit': typeof ApplicationsIdEditRoute
  '/cv/tailor/history': typeof CvTailorHistoryRoute
  '/qa/$id/edit': typeof QaIdEditRoute
  '/applications/$id/': typeof ApplicationsIdIndexRoute
  '/cv/$id/': typeof CvIdIndexRoute
  '/cv/tailor/': typeof CvTailorIndexRoute
  '/qa/$id/': typeof QaIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/applications/new': typeof ApplicationsNewRoute
  '/cv/upload': typeof CvUploadRoute
  '/qa/new': typeof QaNewRoute
  '/applications': typeof ApplicationsIndexRoute
  '/cv': typeof CvIndexRoute
  '/qa': typeof QaIndexRoute
  '/api/ai/stream': typeof ApiAiStreamRoute
  '/applications/$id/edit': typeof ApplicationsIdEditRoute
  '/cv/tailor/history': typeof CvTailorHistoryRoute
  '/qa/$id/edit': typeof QaIdEditRoute
  '/applications/$id': typeof ApplicationsIdIndexRoute
  '/cv/$id': typeof CvIdIndexRoute
  '/cv/tailor': typeof CvTailorIndexRoute
  '/qa/$id': typeof QaIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/applications/$id': typeof ApplicationsIdRouteWithChildren
  '/applications/new': typeof ApplicationsNewRoute
  '/cv/upload': typeof CvUploadRoute
  '/qa/$id': typeof QaIdRouteWithChildren
  '/qa/new': typeof QaNewRoute
  '/applications/': typeof ApplicationsIndexRoute
  '/cv/': typeof CvIndexRoute
  '/qa/': typeof QaIndexRoute
  '/api/ai/stream': typeof ApiAiStreamRoute
  '/applications/$id/edit': typeof ApplicationsIdEditRoute
  '/cv/tailor/history': typeof CvTailorHistoryRoute
  '/qa/$id/edit': typeof QaIdEditRoute
  '/applications/$id/': typeof ApplicationsIdIndexRoute
  '/cv/$id/': typeof CvIdIndexRoute
  '/cv/tailor/': typeof CvTailorIndexRoute
  '/qa/$id/': typeof QaIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applications/$id'
    | '/applications/new'
    | '/cv/upload'
    | '/qa/$id'
    | '/qa/new'
    | '/applications/'
    | '/cv/'
    | '/qa/'
    | '/api/ai/stream'
    | '/applications/$id/edit'
    | '/cv/tailor/history'
    | '/qa/$id/edit'
    | '/applications/$id/'
    | '/cv/$id/'
    | '/cv/tailor/'
    | '/qa/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/applications/new'
    | '/cv/upload'
    | '/qa/new'
    | '/applications'
    | '/cv'
    | '/qa'
    | '/api/ai/stream'
    | '/applications/$id/edit'
    | '/cv/tailor/history'
    | '/qa/$id/edit'
    | '/applications/$id'
    | '/cv/$id'
    | '/cv/tailor'
    | '/qa/$id'
  id:
    | '__root__'
    | '/'
    | '/applications/$id'
    | '/applications/new'
    | '/cv/upload'
    | '/qa/$id'
    | '/qa/new'
    | '/applications/'
    | '/cv/'
    | '/qa/'
    | '/api/ai/stream'
    | '/applications/$id/edit'
    | '/cv/tailor/history'
    | '/qa/$id/edit'
    | '/applications/$id/'
    | '/cv/$id/'
    | '/cv/tailor/'
    | '/qa/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplicationsIdRoute: typeof ApplicationsIdRouteWithChildren
  ApplicationsNewRoute: typeof ApplicationsNewRoute
  CvUploadRoute: typeof CvUploadRoute
  QaIdRoute: typeof QaIdRouteWithChildren
  QaNewRoute: typeof QaNewRoute
  ApplicationsIndexRoute: typeof ApplicationsIndexRoute
  CvIndexRoute: typeof CvIndexRoute
  QaIndexRoute: typeof QaIndexRoute
  ApiAiStreamRoute: typeof ApiAiStreamRoute
  CvTailorHistoryRoute: typeof CvTailorHistoryRoute
  CvIdIndexRoute: typeof CvIdIndexRoute
  CvTailorIndexRoute: typeof CvTailorIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa/': {
      id: '/qa/'
      path: '/qa'
      fullPath: '/qa/'
      preLoaderRoute: typeof QaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv/': {
      id: '/cv/'
      path: '/cv'
      fullPath: '/cv/'
      preLoaderRoute: typeof CvIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/': {
      id: '/applications/'
      path: '/applications'
      fullPath: '/applications/'
      preLoaderRoute: typeof ApplicationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa/new': {
      id: '/qa/new'
      path: '/qa/new'
      fullPath: '/qa/new'
      preLoaderRoute: typeof QaNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa/$id': {
      id: '/qa/$id'
      path: '/qa/$id'
      fullPath: '/qa/$id'
      preLoaderRoute: typeof QaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv/upload': {
      id: '/cv/upload'
      path: '/cv/upload'
      fullPath: '/cv/upload'
      preLoaderRoute: typeof CvUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/new': {
      id: '/applications/new'
      path: '/applications/new'
      fullPath: '/applications/new'
      preLoaderRoute: typeof ApplicationsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/$id': {
      id: '/applications/$id'
      path: '/applications/$id'
      fullPath: '/applications/$id'
      preLoaderRoute: typeof ApplicationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa/$id/': {
      id: '/qa/$id/'
      path: '/'
      fullPath: '/qa/$id/'
      preLoaderRoute: typeof QaIdIndexRouteImport
      parentRoute: typeof QaIdRoute
    }
    '/cv/tailor/': {
      id: '/cv/tailor/'
      path: '/cv/tailor'
      fullPath: '/cv/tailor/'
      preLoaderRoute: typeof CvTailorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv/$id/': {
      id: '/cv/$id/'
      path: '/cv/$id'
      fullPath: '/cv/$id/'
      preLoaderRoute: typeof CvIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/$id/': {
      id: '/applications/$id/'
      path: '/'
      fullPath: '/applications/$id/'
      preLoaderRoute: typeof ApplicationsIdIndexRouteImport
      parentRoute: typeof ApplicationsIdRoute
    }
    '/qa/$id/edit': {
      id: '/qa/$id/edit'
      path: '/edit'
      fullPath: '/qa/$id/edit'
      preLoaderRoute: typeof QaIdEditRouteImport
      parentRoute: typeof QaIdRoute
    }
    '/cv/tailor/history': {
      id: '/cv/tailor/history'
      path: '/cv/tailor/history'
      fullPath: '/cv/tailor/history'
      preLoaderRoute: typeof CvTailorHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/$id/edit': {
      id: '/applications/$id/edit'
      path: '/edit'
      fullPath: '/applications/$id/edit'
      preLoaderRoute: typeof ApplicationsIdEditRouteImport
      parentRoute: typeof ApplicationsIdRoute
    }
    '/api/ai/stream': {
      id: '/api/ai/stream'
      path: '/api/ai/stream'
      fullPath: '/api/ai/stream'
      preLoaderRoute: typeof ApiAiStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApplicationsIdRouteChildren {
  ApplicationsIdEditRoute: typeof ApplicationsIdEditRoute
  ApplicationsIdIndexRoute: typeof ApplicationsIdIndexRoute
}

const ApplicationsIdRouteChildren: ApplicationsIdRouteChildren = {
  ApplicationsIdEditRoute: ApplicationsIdEditRoute,
  ApplicationsIdIndexRoute: ApplicationsIdIndexRoute,
}

const ApplicationsIdRouteWithChildren = ApplicationsIdRoute._addFileChildren(
  ApplicationsIdRouteChildren,
)

interface QaIdRouteChildren {
  QaIdEditRoute: typeof QaIdEditRoute
  QaIdIndexRoute: typeof QaIdIndexRoute
}

const QaIdRouteChildren: QaIdRouteChildren = {
  QaIdEditRoute: QaIdEditRoute,
  QaIdIndexRoute: QaIdIndexRoute,
}

const QaIdRouteWithChildren = QaIdRoute._addFileChildren(QaIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplicationsIdRoute: ApplicationsIdRouteWithChildren,
  ApplicationsNewRoute: ApplicationsNewRoute,
  CvUploadRoute: CvUploadRoute,
  QaIdRoute: QaIdRouteWithChildren,
  QaNewRoute: QaNewRoute,
  ApplicationsIndexRoute: ApplicationsIndexRoute,
  CvIndexRoute: CvIndexRoute,
  QaIndexRoute: QaIndexRoute,
  ApiAiStreamRoute: ApiAiStreamRoute,
  CvTailorHistoryRoute: CvTailorHistoryRoute,
  CvIdIndexRoute: CvIdIndexRoute,
  CvTailorIndexRoute: CvTailorIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
